### ISSUE TITLE
モデルビュー 共分散 一つの変数につき複数定義

### ISSUE THREAD

**Issue by ash1day** [likr/interactive-sem#47]
`y1 ~~ y2`
を定義した状態で
`y1 ~~ y3`
を追加すると上書きされる。
y1をキーとしているから?

`y1 ~~ y2 + y3` としたい

**Comment by likr** [comment]
左辺をキーとするのではなく、二変数のペアの配列で保持する。

**Comment by likr** [comment]
ここの判定が原因な気がする。
https://github.com/likr/interactive-sem/blob/master/src/domain/model/model.ts#L35-L39
